name: ESP32 Build & Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Cache PlatformIO packages
      uses: actions/cache@v3
      id: cache-platformio
      with:
        path: |
          ~/.platformio/packages
          ~/.platformio/lib
        key: ${{ runner.os }}-platformio-${{ hashFiles('**/platformio.ini') }}
        restore-keys: |
          ${{ runner.os }}-platformio-

    - name: Instal PlatformIO CLI
      run: |
        python -m pip install --upgrade pip
        pip install --user platformio
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Instal dependencies
      run: pio update

    - name: Build firmware
      run: pio run

    - name: Upload final build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: .pio/build/**
